const gifItemsData = [
  {
    "userId": 1,
    "id": 0,
    "title": "Типичный юзер",
    "description": "В каждом из нас программист",
    "category" : "Животные",
    "imageSrc": "img/gif/gif-1-prev.gif",
    "gifSrc": "img/gif/gif-1.gif",
    "imageAlt": "crazy cat",
    "likes" : 13,
  },
  {
    "userId": 2,
    "id": 1,
    "title": "Рыжая",
    "description": "У рыжих нет души",
    "category" : "Люди",
    "imageSrc": "img/gif/gif-2-prev.gif",
    "gifSrc": "img/gif/gif-2.gif",
    "imageAlt": "Рижая",
    "likes" : 11,
  },
  {
    "userId": 3,
    "id": 2,
    "title": "Когда любишь порядок",
    "description": "Все вещи должны быть на своем месте",
    "category" : "Люди",
    "imageSrc": "img/gif/gif-3-prev.gif",
    "gifSrc": "img/gif/gif-3.gif",
    "imageAlt": "Когда любишь порядок",
    "likes" : 12,
  },
  {
    "userId": 2,
    "id": 3,
    "title": "Science, bitch",
    "description": "У этого учителя не хочется прогуливать уроки химии",
    "category" : "Наука",
    "imageSrc": "img/gif/gif-4-prev.gif",
    "gifSrc": "img/gif/gif-4.gif",
    "imageAlt": "Science",
    "likes" : 20,
  },
  {
    "userId": 4,
    "id": 4,
    "title": "Учим новичка решать задачи",
    "description": "Тяжело в учении, легко в бою",
    "category" : "Люди",
    "imageSrc": "img/gif/gif-5-prev.gif",
    "gifSrc": "img/gif/gif-5.gif",
    "imageAlt": "Новичек",
    "likes" : 20,
  },
  {
    "userId": 6,
    "id": 5,
    "title": "Конец рабочего дня",
    "description": "Когда хорошо поработал",
    "category" : "Люди",
    "imageSrc": "img/gif/gif-6-prev.gif",
    "gifSrc": "img/gif/gif-6.gif",
    "imageAlt": "Отдых",
    "likes" : 18,
  },
  {
    "userId": 6,
    "id": 6,
    "title": "Премии на моей бывшей работе",
    "description": "Горькая правда",
    "category" : "Люди",
    "imageSrc": "img/gif/gif-7-prev.gif",
    "gifSrc": "img/gif/gif-7.gif",
    "imageAlt": "Премии на работе",
    "likes" : 11,
  },
  {
    "userId": 7,
    "id": 7,
    "title": "Unstoppable",
    "description": "Мастер 80 лвл",
    "category" : "Видеоигры",
    "imageSrc": "img/gif/gif-8-prev.gif",
    "gifSrc": "img/gif/gif-8.gif",
    "imageAlt": "Unstoppable",
    "likes" : 11,
  },
  {
    "userId": 8,
    "id": 8,
    "title": "Енотик",
    "description": "Енотик бежит на стажировку",
    "category" : "Животные",
    "imageSrc": "img/gif/gif-9-prev.gif",
    "gifSrc": "img/gif/gif-9.gif",
    "imageAlt": "Енотик бежит на стажировку",
    "likes" : 11,
  },
  {
    "userId": 9,
    "id": 9,
    "title": "Восторг",
    "description": "Когда видишь своего кумира",
    "category" : "Люди",
    "imageSrc": "img/gif/gif-10-prev.gif",
    "gifSrc": "img/gif/gif-10.gif",
    "imageAlt": "Восторг",
    "likes" : 11,
  },
  {
    "userId": 8,
    "id": 10,
    "title": "Жестокий спорт",
    "description": "Это футбол, детка",
    "category" : "Спорт",
    "imageSrc": "img/gif/gif-11-prev.gif",
    "gifSrc": "img/gif/gif-11.gif",
    "imageAlt": "Жестокий спорт",
    "likes" : 11,
  },
  {
    "userId": 7,
    "id": 11,
    "title": "Треуголик",
    "description": "Красиво вертится",
    "category" : "Наука",
    "imageSrc": "img/gif/gif-12-prev.gif",
    "gifSrc": "img/gif/gif-12.gif",
    "imageAlt": "Треуголик",
    "likes" : 12,
  },
  {
    "userId": 7,
    "id": 12,
    "title": "Колесо опаздывает на встречу",
    "description": "Когда нажал тревожную кнопку под столом, а магазин под охраной автоботов.",
    "category" : "Приколы",
    "imageSrc": "img/gif/gif-13-prev.gif",
    "gifSrc": "img/gif/gif-13.gif",
    "imageAlt": "Колесо опаздывает на встречу",
    "likes" : 24,
  }, 
  {
    "userId": 2,
    "id": 13,
    "title": "Отличные витаминки",
    "description": "Бодрят не по детски",
    "category" : "Люди",
    "imageSrc": "img/gif/gif-14-prev.gif",
    "gifSrc": "img/gif/gif-14.gif",
    "imageAlt": "Отличные витаминки",
    "likes" : 22,
  },  
  {
    "userId": 4,
    "id": 14,
    "title": "Кот-ненависть",
    "description": "котяра",
    "category" : "Животные",
    "imageSrc": "img/gif/gif-15-prev.gif",
    "gifSrc": "img/gif/gif-15.gif",
    "imageAlt": "Кот-ненависть",
    "likes" : 32,
  },
  {
    "userId": 3,
    "id": 15,
    "title": "Командная работа",
    "description": "Когда попросил коллег помочь исправить баг",
    "category" : "Приколы",
    "imageSrc": "img/gif/gif-16-prev.gif",
    "gifSrc": "img/gif/gif-16.gif",
    "imageAlt": "Командная работа",
    "likes" : 54,
  },
  {
    "userId": 6,
    "id": 16,
    "title": "Доминирование",
    "description": "Когда показываешь новичку как ты используешь любимый фреймворк",
    "category" : "Приколы",
    "imageSrc": "img/gif/gif-17-prev.gif",
    "gifSrc": "img/gif/gif-17.gif",
    "imageAlt": "Доминирование",
    "likes" : 14,
  },
  {
    "userId": 7,
    "id": 17,
    "title": "Battlefield",
    "description": "Когда лучше подождать",
    "category" : "Видеоигры",
    "imageSrc": "img/gif/gif-18-prev.gif",
    "gifSrc": "img/gif/gif-18.gif",
    "imageAlt": "Battlefield",
    "likes" : 14,
  },
  {
    "userId": 6,
    "id": 18,
    "title": "Рыбак",
    "description": "Новая техника рыбалки",
    "category" : "Люди",
    "imageSrc": "img/gif/gif-19-prev.gif",
    "gifSrc": "img/gif/gif-19.gif",
    "imageAlt": "Рыбак",
    "likes" : 14,
  },
  {
    "userId": 3,
    "id": 19,
    "title": "Твоя девушка, когда слышит комплимент",
    "description": "Чихуа",
    "category" : "Животные",
    "imageSrc": "img/gif/gif-20-prev.gif",
    "gifSrc": "img/gif/gif-20.gif",
    "imageAlt": "Твоя девушка, когда слышит комплимент",
    "likes" : 14,
  },
  {
    "userId": 8,
    "id": 20,
    "title": "Пикачу",
    "description": "Пика пика",
    "category" : "Животные",
    "imageSrc": "img/gif/gif-21-prev.gif",
    "gifSrc": "img/gif/gif-21.gif",
    "imageAlt": "Пикачу",
    "likes" : 14,
  },
  {
    "userId": 9,
    "id": 21,
    "title": "Nemo",
    "description": "movie",
    "category" : "Животные",
    "imageSrc": "img/gif/gif-22-prev.gif",
    "gifSrc": "img/gif/gif-22.gif",
    "imageAlt": "Nemo",
    "likes" : 14,
  }, 
  {
    "userId": 2,
    "id": 22,
    "title": "Em",
    "description": "Eminem - Without me",
    "category" : "Люди",
    "imageSrc": "img/gif/gif-23-prev.gif",
    "gifSrc": "img/gif/gif-23.gif",
    "imageAlt": "Em",
    "likes" : 26,
  },
  {
    "userId": 2,
    "id": 22,
    "title": "Tom",
    "description": "Том",
    "category" : "Животные",
    "imageSrc": "img/gif/gif-24-prev.gif",
    "gifSrc": "img/gif/gif-24.gif",
    "imageAlt": "Tom",
    "likes" : 13,
  },

]